# Generated by Django 4.0.4 on 2022-07-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=128)),
                ('min_price', models.PositiveIntegerField(blank=True)),
                ('max_price', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
    ]
