# Generated by Django 4.0.6 on 2022-07-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='posted_date',
        ),
    ]
