# Generated by Django 4.0.6 on 2022-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_date_post_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateField(auto_now=True),
        ),
    ]
