# Generated by Django 4.0.6 on 2022-07-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_officialposition_field_officialposition_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position_name', to='post.officialposition'),
        ),
    ]
